'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { chromium } = require('playwright-core');
const { Client } = require('@modelcontextprotocol/sdk/client/index.js');
const { StdioClientTransport } = require('@modelcontextprotocol/sdk/client/stdio.js');
const { startBrowserShare } = require('../src/browser-share');

test('MCP discovers shared tabs and operates the same page using DOM and screenshots', async t => {
  const browser = await chromium.launch({ executablePath: process.env.BROWSER_EXECUTABLE || '/usr/bin/google-chrome', headless: true, args: ['--no-sandbox'] });
  t.after(() => browser.close());
  const page = await browser.newPage({ viewport: { width: 800, height: 600 } });
  const fixture = '<label>Name<input id="name" aria-label="Name"></label><button id="save" onclick="this.textContent=document.querySelector(\'input\').value">Save</button><div id="drag" style="width:200px;height:100px;background:skyblue" onpointerdown="this.textContent=\'Dragging\'" onpointerup="this.textContent=\'Dropped\'"></div>';
  await page.route('http://fixture.local/**', route => route.fulfill({ body: fixture, contentType: 'text/html' }));
  await page.goto('http://fixture.local/');
  const share = await startBrowserShare({ page, postState: async () => {}, captureFrame: async () => {} });
  t.after(() => share.close());
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'browser-mcp-test-'));
  const tabId = 'a'.repeat(24);
  const sessionFile = path.join(directory, `${tabId}.json`);
  t.after(async () => { await fs.unlink(sessionFile).catch(() => {}); await fs.rmdir(directory); });
  const client = new Client({ name: 'browser-test', version: '1.0.0' });
  await client.connect(new StdioClientTransport({ command: process.execPath, args: [path.resolve(__dirname, '../src/browser-mcp.js'), directory], stderr: 'pipe' }));
  t.after(() => client.close());
  const call = (name, args = {}) => client.callTool({ name: `browser_${name}`, arguments: name === 'tabs' ? {} : { tabId, ...args } });
  const data = result => JSON.parse(result.content[0].text);
  assert.equal(data(await call('tabs')).tabs.length, 0);
  await fs.writeFile(sessionFile, JSON.stringify({ endpoint: share.endpoint, token: share.token }), { mode: 0o600 });
  const tools = await client.listTools();
  assert(tools.tools.some(tool => tool.name === 'browser_drag'));
  assert.equal(data(await call('tabs')).tabs[0].tabId, tabId);
  const dom = data(await call('dom'));
  assert(dom.elements.some(e => e.selector === '#save'));
  await call('fill', { selector: '#name', text: 'MCP' });
  const rect = dom.elements.find(e => e.selector === '#save').rect;
  await call('click_xy', { x: rect.x + 5, y: rect.y + 5 });
  assert.equal(await page.locator('#save').innerText(), 'MCP');
  const shot = await call('screenshot');
  assert.equal(shot.content[0].type, 'image');
  assert.equal(Buffer.from(shot.content[0].data, 'base64').subarray(1, 4).toString(), 'PNG');
  await call('click', { selector: '#name' });
  await call('press', { key: 'Control+A' });
  await call('type', { text: 'Typed through MCP' });
  assert.equal(await page.locator('#name').inputValue(), 'Typed through MCP');
  const box = await page.locator('#drag').boundingBox();
  await call('drag', { x: box.x + 10, y: box.y + 10, toX: box.x + 100, toY: box.y + 50 });
  assert.equal(await page.locator('#drag').innerText(), 'Dropped');
  assert.equal((await call('click_xy', { x: 900, y: 0 })).isError, true);
  await call('reload');
  assert.equal(await page.locator('#save').innerText(), 'Save');
  assert.match(data(await call('inspect')).snapshot, /Save/);
  share.close();
  assert.equal((await call('click', { selector: '#save' })).isError, true);
  assert.equal(data(await call('tabs')).tabs.length, 0);
  assert.equal((await call('inspect', { tabId: '../outside' })).isError, true);
});
